version: '3.1'
services:
  stats-server:
    build: ./stats/server
    image: stats
    container_name: ewm-stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - DB_NAME=ewmstat
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    container_name: ewmstat_database_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstat
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: service
    image: service
    container_name: ewm-servive-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - DB_NAME=ewm
      - DB_HOST=ewm-db
      - DB_PORT=5432

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewmservice_database_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
